name: Docker

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  IMAGE_NAME: kivy/buildozer
  SHOULD_PUBLISH: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) }}

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: ${{ env.SHOULD_PUBLISH == 'true' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Multi-platform Image
        uses: docker/build-push-action@v6
        with:
          push: ${{ env.SHOULD_PUBLISH == 'true' }}
          tags: ${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: ${{ env.SHOULD_PUBLISH == 'true' && format('type=registry,ref={0}:latest,mode=max', env.IMAGE_NAME) || '' }}
      - name: Local Build for Testing
        uses: docker/build-push-action@v6
        with:
          # Load image into local Docker daemon
          load: true
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          tags: ${{ env.IMAGE_NAME }}:latest
      # Run the locally built image to test it
      - name: Docker run
        run: docker run ${{ env.IMAGE_NAME }} --version

  update-readme:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: peter-evans/dockerhub-description@v4
        if: ${{ env.SHOULD_PUBLISH == 'true' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE_NAME }}
          readme-filepath: README.md
